version: '3'
services:
  app:
    container_name: alura_api_studies
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:80
    volumes:
      - .:/var/www/html/alura_api_studies
    environment:
      UID: ${UID:-1001}
      GID: ${GID:-1001}
    

